[build]
  publish = "out"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# API routes redirect to Netlify Functions
[[redirects]]
  from = "/api/careers"
  to = "/.netlify/functions/careers"
  status = 200

[[redirects]]
  from = "/api/lead"
  to = "/.netlify/functions/lead"
  status = 200

[[redirects]]
  from = "/api/demo/send"
  to = "/.netlify/functions/demo-send"
  status = 200

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Static files
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Functions configuration
[functions]
  directory = "netlify/functions"

# Edge functions (if needed)
[[edge_functions]]
  function = "hello"
  path = "/hello"
